// packages/vue/src/Scripts/index.vue
<template>
  <div>
    <template v-for="(s, i) in data.scripts">
      <component
        v-if="s.html"
        :is="'script'"
        :key="i"
        v-html="s.html"
        {{...s.attr}}
      ></component>
      <component v-else :is="'script'" {{...s.attr}}></component>
    </template>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    data: {
      type: Object,
      required: true,
    },
  },
};
</script>

// apps/web/src/components/Scripts/index.tsx
import Script from "next/script";
import React, { ReactElement } from "react";
import { getScripts } from "ui";

export interface Props {
  data: Array<string>;
}

export const Scripts = (props: Props): ReactElement => {
  const scripts = getScripts(props.data);

  return (
    <>
      {scripts.map((s, i) =>
        s.html ? (
          <Script
            key={i}
            {...s.attr}
            dangerouslySetInnerHTML={{ __html: s.html }}
          />
        ) : (
          <Script key={i} {...s.attr}></Script>
        )
      )}
    </>
  );
};
