// examples/nextjs/src/components/Header/index.tsx
import React, { CSSProperties, ReactElement } from "react";

const styles: CSSProperties = {
  height: "80px",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "column",
  backgroundColor: "antiquewhite",
};

export const Header = (): ReactElement => (
  <header style={styles}>
    <h1>Services page</h1>
  </header>
);

// examples/nuxtjs/src/components/Header/index.vue
<template>
  <header :style="styles">
    <h1>Services page</h1>
  </header>
</template>

<script>
export default {
  name: "Header",
  data() {
    return {
      styles: {
        height: "80px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        backgroundColor: "antiquewhite",
      },
    };
  },
};
</script>
