// packages/vue/src/Styles/index.vue
<template>
  <div>
    <template v-for="(s, i) in data.styles">
      <link v-if="s.type === 'link'" :key="i" {{...s.attr}} />
      <component v-else :is="'style'" v-html="s.html" {{...s.attr}} />
    </template>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    data: {
      type: Object,
      required: true,
    },
  },
};
</script>

// packages/react/src/Styles/index.tsx
import { Assets } from "@brizy/assetmanager/dist/types";
import { ReactElement } from "react";

export interface Props {
  data: Assets;
}

export const Styles = (props: Props): ReactElement => {
  const data = props.data;

  return (
    <>
      {data.styles.map((s, i) =>
        s.type === "link" ? (
          <link key={i} {...s.attr} />
        ) : (
          <style
            key={i}
            {...s.attr}
            dangerouslySetInnerHTML={{ __html: s.html }}
          />
        )
      )}
    </>
  );
};
