// examples/nuxtjs/src/pages/index.vue
<template>
  <BuilderComponent :data="responseData" />
</template>

<script setup>
import { API } from "../utils/api";
import { BuilderComponent } from "@brizy/vue";
import { ref } from "vue";
import { useRoute } from "vue-router";

const { params } = useRoute();
const [item] = params.all ?? [];
const responseData = ref(null);
const api = API.getInstance();
const response = await api.getHTMLByItem({
  collection: "page",
  item: item,
});
if (!response) {
  throw Error(`Fail to get html, ${response}`);
}
responseData.value = response;
console.log("data response", responseData);
</script>

// examples/reactjs/src/pages/page.tsx
import { API } from "../api";
import { BuilderComponent, CompilerData } from "@brizy/react";
import { ReactElement, useEffect, useState } from "react";
import { useLocation } from "react-router-dom";

const Page = (): ReactElement => {
  const location = useLocation();
  const path = location.pathname.substring(1);

  const [page, setPage] = useState<CompilerData>();
  const [error, setError] = useState<Error | null>(null);

  const fetchData = async () => {
    const api = API.getInstance();

    try {
      const data = await api.getHTMLByItem({
        collection: "page",
        item: path,
      });

      setPage(data);
    } catch (e) {
      setError(e as Error);
    }
  };

  useEffect(() => {
    fetchData();
  }, [path]);

  if (error) {
    return <h1>Error: {error.message}</h1>;
  }

  if (!page) {
    return <h1>Loading...</h1>;
  }

  return <BuilderComponent data={page} />;
};

export default Page;
