// apps/web/src/components/Styles/index.tsx
import React, { ReactElement } from "react";
import { getStyles } from "ui";

export interface Props {
  data: Array<string>;
}

export const Styles = (props: Props): ReactElement => {
  const styles = getStyles(props.data);

  return (
    <>
      {styles.map((style, i) => {
        if (style.type === "link") {
          return <link key={i} {...style.attr} />;
        }

        return (
          <style
            key={i}
            {...style.attr}
            dangerouslySetInnerHTML={{ __html: style.html }}
          />
        );
      })}
    </>
  );
};

// packages/vue/src/Styles/index.vue
<template>
  <div>
    <template v-for="(s, i) in data.styles">
      <link v-if="s.type === 'link'" :key="i" {{...s.attr}} />
      <component v-else :is="'style'" v-html="s.html" {{...s.attr}} />
    </template>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    data: {
      type: Object,
      required: true,
    },
  },
};
</script>
