// packages/vue/src/Builder/index.vue
<template>
  <div>
    <div v-if="builderState.status === 'error'" class="error-message">
      {{ builderState.error }}
    </div>
    <div v-else style="height: 100vh" class="container__editor" ref="containerRef"></div>
    <script src="https://cdn.brizylocal.com/pages/2.1.35/index.js"></script>
  </div>
</template>

<script>
import { useEditor } from "src/hooks/useEditor/index.vue";
import { ref, onMounted } from "vue";

export default {
  props: {
    token: String,
    pageData: Object,
    projectData: Object,
    pagePreview: String,
  },
  setup(props) {
    const containerRef = ref(null);

    const config = {
      pageData: props.pageData,
      projectData: props.projectData,
      pagePreview: props.pagePreview,
      container: containerRef.value,
      htmlOutputType: "monolith",
      onSave: (data) => {
        console.log(data);
      },
    };

    const [builderState] = useEditor(props.token, config);

    onMounted(() => {
      const script = document.createElement("script");
      script.src = "https://cdn.brizylocal.com/pages/2.1.35/index.js";
      document.body.appendChild(script);
    });

    return {
      containerRef,
      builderState,
    };
  },
};
</script>

// packages/react/src/Builder/index.tsx
import { useEditor } from "@/hooks/useEditor";
import { Config } from "@/hooks/useEditor/types";
import { FC, useRef } from "react";

export interface Props {
  token: string;
  pageData: Record<string, unknown>;
  projectData: Record<string, unknown>;
  pagePreview: string;
}

export const Builder: FC<Props> = (props) => {
  const { token, pageData, projectData, pagePreview } = props;
  const containerRef = useRef<HTMLDivElement>(null);

  const config: Config<"monolith"> = {
    pageData,
    projectData,
    pagePreview,
    container: containerRef.current,
    htmlOutputType: "monolith",

    onSave: (data) => {
      console.log(data);
    },
  };
  const [builderState] = useEditor(token, config);

  return (
    <>
      {builderState.status === "error" ? (
        builderState.error
      ) : (
        <div
          style={{ height: "100vh" }}
          className="container__editor"
          ref={containerRef}
        />
      )}
      <script src="https://cdn.brizylocal.com/pages/3.0.1/index.js"></script>
    </>
  );
};
