// examples/nextjs/src/components/Footer/index.tsx
import React, { CSSProperties, ReactElement } from "react";

const styles: CSSProperties = {
  height: "80px",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "column",
  backgroundColor: "antiquewhite",
};

export const Footer = (): ReactElement => (
  <footer style={styles}>
    <h4>Footer Copyright</h4>
  </footer>
);

// examples/nuxtjs/src/components/Footer/index.vue
<template>
  <footer :style="styles">
    <h4>Footer Copyright</h4>
  </footer>
</template>

<script>
export default {
  name: "Footer",
  data() {
    return {
      styles: {
        height: "80px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        backgroundColor: "antiquewhite",
      },
    };
  },
};
</script>
