// packages/react/src/BuilderComponent.tsx
import { Scripts } from "./Scripts";
import { Styles } from "./Styles";
import { CompilerData } from "./types";
import { getAssets, getHtml } from "@brizy/assetmanager";
import { ReactElement } from "react";

export interface Props {
  data: CompilerData;
}

export const BuilderComponent = (props: Props): ReactElement => {
  const assets = getAssets(props.data);

  return (
    <>
      <Styles data={assets} />
      <div
        className="brz brz-root__preview"
        dangerouslySetInnerHTML={{ __html: getHtml(props.data) }}
      />
      <Scripts data={assets} />
    </>
  );
};

// packages/vue/src/BuilderComponent.vue
<template>
  <div>
    <Styles :data="assets"></Styles>
    <div class="brz brz-root__preview" v-html="getHtml"></div>
    <Scripts :data="assets"></Scripts>
  </div>
</template>

<script lang="ts">
import Scripts from "./Scripts/index.vue";
import Styles from "./Styles/index.vue";
import type { CompilerData, Assets } from "./types";
import { getAssets, getHtml } from "@brizy/assetmanager";

export default {
  props: {
    data: {
      type: Object as () => CompilerData,
      required: true,
    },
  },
  computed: {
    assets(): Assets {
      return getAssets(this.data);
    },
    getHtml(): string {
      return getHtml(this.data);
    },
  },
  components: {
    Scripts,
    Styles,
  },
};
</script>
