// examples/nextjs/src/app/init/components/base.tsx
"use client";

import { Install, NotFound, Welcome } from "@brizy/docs-react";
import Config from "@config";
import { getUrl } from "@utils/common";
import { useRouter } from "next/navigation";
import React, { FC, useEffect, useMemo, useRef } from "react";

export interface Props {
  token?: string;
}

export const Base: FC<Props> = (props) => {
  const { token } = props;
  const { builderWelcomeUrl } = Config;
  const router = useRouter();
  const mounted = useRef(false);

  const redirectUrl = useMemo(() => {
    return getUrl("/init");
  }, []);

  useEffect(() => {
    if (mounted.current) {
      return;
    }

    mounted.current = true;

    if (token) {
      const refresh = (): void => {
        setTimeout(() => {
          router.refresh();
          refresh();
        }, 7000);
      };

      refresh();
    }
  }, [router, token]);

  return token ? (
    <Install token={token} />
  ) : redirectUrl ? (
    <Welcome href={`${builderWelcomeUrl}?redirectUrl=${redirectUrl}`} />
  ) : (
    <NotFound />
  );
};

// examples/nuxtjs/src/pages/init/components/base.vue
<template>
  <template v-if="token">
    <Install :token="token" />
  </template>
  <template v-else-if="redirectUrl">
    <Welcome :href="`${builderWelcomeUrl}?redirectUrl=${redirectUrl}`" />
  </template>
  <template v-else>
    <NotFound />
  </template>
</template>

<script setup>
import Config from "../../../config/index";
import { getUrl } from "../../../utils/common";
import { Install, NotFound, Welcome } from "@brizy/docs-vue";
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";

const props = defineProps({
  token: String,
});

const { builderWelcomeUrl } = Config;
const router = useRouter();
const mounted = ref(false);

const redirectUrl = ref(getUrl("/init"));

onMounted(() => {
  if (mounted.value) {
    return;
  }

  mounted.value = true;

  if (props.token) {
    const refresh = () => {
      setTimeout(() => {
        router.replace(router.currentRoute.value.fullPath);
        refresh();
      }, 7000);
    };

    refresh();
  }
});
</script>
