// packages/vue/src/Scripts/index.vue
<script lang="ts">
import useLoadScript from "@/hooks/useLoadScript.vue";
import { Assets } from "@brizy/assetmanager/dist/types";
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    data: {
      type: Object as () => Assets,
      required: true,
    },
  },
  setup(props) {
    const isServer = typeof window === "undefined";
    useLoadScript(props.data.scripts);
    return { props, isServer };
  },
});
</script>

<template>
  <div>
    <template v-for="(s, i) in data.scripts">
      <component
        v-if="s.html"
        :is="'script'"
        :key="i"
        v-html="s.html"
        {{...s.attr}}
      ></component>
      <component v-else :is="'script'" {{...s.attr}}></component>
    </template>
    <template v-if="isServer">
      <component>window.isServer = true;</component>
    </template>
  </div>
</template>

// packages/ui/src/Scripts/index.tsx
import { Assets } from "@brizy/assetmanager/dist/types";
import React, { ReactElement } from "react";

export interface Props {
  data: Assets;
}

export const Scripts = (props: Props): ReactElement => {
  const data = props.data;

  return (
    <>
      {data.scripts.map((s, i) =>
        s.html ? (
          <script
            key={i}
            {...s.attr}
            dangerouslySetInnerHTML={{ __html: s.html }}
          />
        ) : (
          <script key={i} {...s.attr}></script>
        )
      )}
    </>
  );
};
