// examples/nuxtjs/src/pages/init/index.vue
<template>
  <Base :token="token" />
</template>

<script setup>
import Base from "./components/base.vue";
import { defineProps } from "vue";

const props = defineProps({
  searchParams: {
    type: Object,
    default: () => ({ token: "" }),
  },
});

const token = props.searchParams.token;
</script>

// examples/nextjs/src/app/init/page.tsx
import { Base } from "./components/base";
import React, { ReactElement } from "react";

interface Props {
  searchParams: { [key: string]: string | undefined };
}

const Init = (props: Props): ReactElement => {
  const token = props.searchParams.token;

  return <Base token={token} />;
};

export default Init;
