// apps/web/src/app/services/page.tsx
import { Footer } from "@components/Footer";
import { Header } from "@components/Header";
import Config from "@config";
import { getHtml } from "@utils/api";
import React, { ReactElement } from "react";
import { Brizy } from "ui";

const Services = async (): Promise<ReactElement> => {
  const apiKey = Config.apiKey;

  if (!apiKey) {
    return (
      <>
        <Header />
        <h1>Missing api keys</h1>
        <Footer />
      </>
    );
  }
  let data;

  try {
    data = await getHtml({
      project: apiKey,
      collection: "page",
      item: "about",
    });
  } catch (e) {
    data = null;
  }

  if (!data) {
    return (
      <>
        <Header />
        <h1>Fail to get html</h1>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Header />

      <Brizy data={data} />

      <Footer />
    </>
  );
};

export default Services;

// examples/nuxtjs/src/pages/services/index.vue
<template>
  <div>
    <Header />
    <BuilderComponent v-if="data" :data="data" />
    <ControlError v-else :error="error" />
    <Footer />
  </div>
</template>

<script setup>
import ControlError from "../../components/ControlError/index.vue";
import Footer from "../../components/Footer/index.vue";
import Header from "../../components/Header/index.vue";
import { API } from "../../utils/api";
import { BuilderComponent } from "@brizy/vue";
import { onMounted, ref } from "vue";

let data = ref(null);
const error = ref(null);

onMounted(async () => {
  try {
    const api = API.getInstance();
    data = await api.getHTMLByItem({
      collection: "page",
      item: "about",
    });
  } catch (e) {
    error.value = e;
  }
});
</script>
